[OMHD-433]: Toast text not visible in dark mode on Android 13
openmobilehub/android-omh-auth pull request #89
Opened 2024-07-10 12:24 UTC by andrei-zgirvaci

## Summary

## Demo
![Demo Preview]()

## Checklist:
- [ ] Documentation is up to date to reflect these changes
- [ ] Created Unit tests

Closes: [OMHD-433](https://callstackio.atlassian.net/browse/OMHD-433)

2024-07-10 13:19 UTC, DamianNowak5f requested changes

2024-07-10 13:19 UTC, DamianNowak5f commented on apps/auth-sample/src/main/java/com/openmobilehub/android/auth/sample/loggedin/LoggedInFragment.kt
> +        toast.show()
Thats quite a workaround.

The issue can be resolved by upgrading the `targetSdkVersion` from `29` to `34`.

From what I briefly checked it can be done without any updated to the code but I would double check and re-test everything in the app.

The testing will take more time but the current `targetSdkVersion` is extremely low - apps with such target sdk are not even accepted to the Play Store.

2024-07-10 13:38 UTC, andrei-zgirvaci commented on apps/auth-sample/src/main/java/com/openmobilehub/android/auth/sample/loggedin/LoggedInFragment.kt
> +        toast.show()
Implemented.

2024-07-11 10:15 UTC, DamianNowak5f approved these changes

2024-07-11 14:14 UTC, merged